SELECT DECODE(CL.CLM_CORI,'1',CL.clm_cltitle ||' '|| CL.clm_initials ||' '|| CL.clm_name,CL.CLM_NAME)AS CLM_NAME,cl.clm_mailaddline1 || ' ' || cl.clm_mailaddline2 || ' ' || cl.clm_mailaddline3 || ' ' || cl.clm_mailaddline4, CL.CLM_MOBILENO    
FROM LEASEINFO.TBLCONTRACTS C  
INNER JOIN GLINFO.TBLDAILYSUMMARY D ON C.CON_NO = D.DLS_CONNO 
INNER JOIN CORPINFO.TBLCLIENTMAIN CL ON C.CON_CLMCODE = CL.CLM_CODE 
INNER JOIN REALESTATE.TBLPROJECT P ON C.CON_PROJECTID = P.PROJECTID  
WHERE (NVL(D.DLS_ARRCAP,0) + NVL(D.DLS_ARRINT,0) + NVL(D.DLS_ARRTAX,0) + NVL(D.DLS_ARRTAX1,0) + NVL(D.DLS_ARRTAX2,0) + NVL(D.DLS_OTHOUT,0)) = 0  
AND C.CON_BRNCODE = 'HO'  
ORDER BY D.DLS_NOOFARR ;